name: PyLops-MPI (CuPy, CUDA-Aware MPI)

on:
  workflow_dispatch:

jobs:
  build-mpi:
    strategy:
      matrix:
        rank: ['2']
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment and Install dependencies and pylops
        run: |
          export PATH=/u/yuxihong/workspace/local/openmpi_cudaaware_install/bin:$PATH
          python3 -m venv .venv-pylops
          # write install scripts
          cat << 'EOF' > pylops_tests.sh
          #!/bin/bash
          PYTHON=.venv-pylops/bin/python3
          PIP=.venv-pylops/bin/pip
          ls $PYTHON
          ls $PIP
          $PIP install --upgrade pip setuptools
          $PIP install flake8 pytest setuptools-scm
          $PIP install -r requirements-dev.txt
          $PIP install cupy-cuda12x
          $PYTHON -m setuptools_scm
          $PIP install .
          EOF
          which mpirun
          srun --account=yuxilab -n 1 -N 1 --gres=gpu:L40S:1 bash pylops_tests.sh
      - name: Tests with pytest 
        run: |
          export PATH=/u/yuxihong/workspace/local/openmpi_cudaaware_install/bin:$PATH
          which mpirun
          srun --account=yuxilab -n 1 -N 1 --gres=gpu:L40S:1 --mpi=list
